### ISSUE TITLE
Non-helpful exception when class test name does not match test filename

### ISSUE THREAD

**Issue by mikey179** [xp-framework/unittest#17] opened 2016-01-11 13:13 UTC
When the name of the test class does not match the name from the test file a `lang.reflect.TargetInvocationException` is thrown which contains a bug and is also not helpful for the user. For instance, if you create the test `DepartmentAutoDomainsTest` but due to some copy and paste bug name the file `DepartmentAutoDomains.class.php` only this will lead to such an exception:

```
Uncaught exception: Exception lang.reflect.TargetInvocationException (xp.unittest.Runner::main)
  at lang.reflect.Method::invoke(NULL, array[1]) [line 350 of class-main.php] 
Caused by Exception lang.ClassFormatException (Class "org.oneandone.trail2elk.unittest.departments.DepartmentAutoDomains" not declared in loaded file)
  at lang.AbstractClassLoader::loadClass0((0x42)'org.oneandone.trail2elk.unittest.departments.DepartmentAutoDomai') [line 415 of ClassLoader.class.php] 
  at lang.ClassLoader::loadClass0((0x42)'org.oneandone.trail2elk.unittest.departments.DepartmentAutoDomai') [line 519 of ClassLoader.class.php] 
  at lang.ClassLoader::loadClass((0x42)'org.oneandone.trail2elk.unittest.departments.DepartmentAutoDomai') [line 832 of XPClass.class.php] 
  at lang.XPClass::forName((0x42)'org.oneandone.trail2elk.unittest.departments.DepartmentAutoDomai') [line 68 of FolderSource.class.php] 
  at xp.unittest.sources.FolderSource::testCasesWith(array[0]) [line 349 of Runner.class.php] 
  at xp.unittest.Runner::run(array[1]) [line 380 of Runner.class.php] 
  at xp.unittest.Runner::main(array[1]) [line 0 of StackTraceElement.class.php] 
  at ReflectionMethod::invokeArgs(NULL, array[1]) [line 90 of Method.class.php] 
```

First, the class name in the stack trace is shortened by two characters from the original class name. Second, the exception itself doesn't help in finding the cause. The test runner should be smart enough to detect that file name and class name do not match and should print an according error message that is helpful for the user to see what is actually wrong.

**Comment by thekid** [comment] 2016-01-11 15:02
Thanks - this needs to be addressed in `xp-framework/core`, this is nothing the test runner needs to influence.

**Comment by thekid** [comment] 2016-01-11 15:03
The filename is intract in the message itself:

`Caused by Exception lang.ClassFormatException  (Class "org.oneandone.trail2elk.unittest.departments.DepartmentAutoDomains" not declared in loaded file)`

Stack trace elements don't show complete strings... this could include a shortening marker though, something like `...`

**Comment by thekid** [comment] 2016-01-12 08:35
Easiest way to reproduce:

``` sh
friebe@wirearchy ~
$ cat Test.class.php
<?php

# Alternatively
$ cat Test.class.php
<?php

class TrialAndError {
}

# In both cases:
friebe@wirearchy ~
$ xp Test
Uncaught exception: Exception lang.ClassFormatException (Class "Test" not declared in loaded file)
  at lang.AbstractClassLoader::loadClass0((0x4)'Test') [line 425 of ClassLoader.class.php]
  at lang.ClassLoader::loadClass0((0x4)'Test') [line 529 of ClassLoader.class.php]
  at lang.ClassLoader::loadClass((0x4)'Test') [line 346 of class-main.php]
```

**Closed as completed** 2016-01-12 13:59 UTC
